sudo: true
language: c
cache:
  apt: true
  ccache: true
services: docker

addons:
  hosts:
    - mariadb.example.com

before_script:
  # Disable services enabled by default
  - sudo /etc/init.d/mysql stop

before_install:
  - chmod -R +x .travis/*
  - chmod 777 .travis/build/
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp
matrix:
  allow_failures:
#    - env: DB=build
#    - env: SERVER_BRANCH=10.5
#    - env: SERVER_BRANCH=10.5 TEST_OPTION=--ps-protocol
  include:
    - env: DB=build
    - env: SKYSQL=true
# disable for now    - env: DB=mysql:8.0
    - env: DB=mariadb:10.1
    - env: DB=mariadb:10.2
    - env: DB=mariadb:10.3
    - env: DB=mariadb:10.4
    - env: SERVER_BRANCH=10.2
    - env: SERVER_BRANCH=10.2 TEST_OPTION=--ps-protocol
    - env: SERVER_BRANCH=10.3
    - env: SERVER_BRANCH=10.3 TEST_OPTION=--ps-protocol
    - env: SERVER_BRANCH=10.4
    - env: SERVER_BRANCH=10.4 TEST_OPTION=--ps-protocol
    - env: SERVER_BRANCH=10.5
    - env: SERVER_BRANCH=10.5 TEST_OPTION=--ps-protocol

script:
  - if [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - if [ -z "$DB" ] && [ -z "$SKYSQL" ] ; then .travis/server-replace-submodule.sh; fi
  - if [ -n "$DB" ] || [ -n "$SKYSQL" ]; then .travis/script.sh; fi

